apiVersion: v1
kind: Service
metadata: 
  name: drupal-mysql-service
  namespace: drupal
spec: 
  ports: 
    - 
      name: mysql
      port: 3306
      protocol: TCP
  selector: 
    app: drupal-mysql
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: drupal-mysql
  namespace: drupal
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template: 
    metadata: 
      labels: 
        app: drupal-mysql
    spec: 
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: drupal
        - name: MYSQL_PASSWORD
          value: drupal
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_USER
          value: drupal
        image: wodby/mariadb
        name: mariadb
        ports: 
          - 
            containerPort: 3306
            name: mysql
            protocol: TCP
        volumeMounts: 
          - 
            mountPath: /var/lib/mysql
            name: vol-drupal
            subPath: dbdata
      volumes: 
        - 
          name: vol-drupal
          persistentVolumeClaim: 
            claimName: drupal-pvc-mysql
